export const contentGroupSort = ["Universe", "News", "Benkyou", "Utility", "Tools", "Games", "User"];

export const rawContentGrid = {
	//Benkyou
	cl_Analysis: {
		userSelected: true,
		contentGroup: "Benkyou",
		globalValString: "idVin_analysisEntry",
		name: "Analysis-Analyse",
		source: {
			Daten: "https://github.com/syzer/sentiment-analyser/blob/master/SentiWS.txt",
		},
		info: "Lass einen Text oder einzelne Wörter auf ihre Stimmung hin prüfen! Der schlechteste wert ist -10, der beste ist 10",
		subgrid: [
			["cl_AnalysisInput", "right"],
			["cl_AnalysisResult", "center"],
			["cl_AnalysisProgress", "center", "start"],
			["cl_AnalysisNews", "right"],
			["cl_AnalysisWiki", "right"],
			["cl_AnalysisTabResult", "center"],
		],
	},
	cl_SpeechTranslate: {
		userSelected: true,
		contentGroup: "Benkyou",
		globalValString: "idArea_speechFromText",
		name: "Discipuli",
		heritage: ["latein", "Student"],
		subgrid: [
			["cl_SpeechLangSelect", "center"],
			["cl_SpeechVoiceSelect", "center"],
			["cl_SpeechOptions", "center"],
			["cl_SpeechOutputArea", "center"],
		],
	},
	cl_Synonym: {
		userSelected: true,
		contentGroup: "Benkyou",
		globalValString: "idVin_synonymEntry",
		name: "Synonym",
		heritage: ["deutsch", "Ersatzwort"],
		source: {
			Daten: "https://www.openthesaurus.de",
		},
		info: "Finde Synonyme für einen Begriff.",
		subgrid: [
			["cl_SynonymInput", "center"],
			["cl_SynonymSearchword", "center"],
			["cl_SynonymTable", "center"],
		],
	},
	cl_WikiSearch: {
		userSelected: true,
		contentGroup: "Benkyou",
		globalValString: "idVin_wikiInput",
		name: "Wiki-Search",
		source: {
			Code: "https://thecodingtrain.com/CodingChallenges/075-wikipedia-api.html",
		},
		subgrid: [
			["cl_WikiInput", "left"],
			["cl_WikiLanguage", "left"],
			["cl_WikiTable", "left"],
			["cl_WikiResultTitle", "left", "center"],
			["cl_WikiResultText", "center"],
			["cl_WikiResultImage", "center"],
		],
	},
	//Games
	cl_Beatmachine: {
		userSelected: true,
		width: 2,
		contentGroup: "Games",
		name: "Beatmachine",
		heritage: ["englisch", "Rhythmusmaschine"],
		info: "Drumpattern im klassischen Stil erstellen",
		subgrid: [
			["cl_BeatmachineOptionsA", "left"],
			["cl_BeatmachineOptionsB", "left"],
			["cl_BeatmachineOptionsC", "left"],
			["cl_BeatmachineOptionsD", "left"],
			["cl_BeatmachineTracks", "left"],
		],
	},
	cl_Empat: {
		userSelected: true,
		height: 2,
		contentGroup: "Games",
		name: "Sambung Empat",
		heritage: ["malaysisch", "verbinde vier"],
		info: 'Klassisches 4-Gewinnt!Benutze die Maus, die Pfeiltasten oder die Zifferntasten zum bewegen. Mit "Enter" oder "Space" lässt sich ein Stein legen.',
		subgrid: [
			["cl_EmpatInputs", "center"],
			["cl_EmpatCanvas", "center"],
		],
	},
	cl_Ibhaluni: {
		userSelected: true,
		height: 2,
		contentGroup: "Games",
		name: "Ibhaluni",
		heritage: ["zulu", "Ballon"],
		source: {
			Hintergrundbild: "https://opengameart.org/content/flappy-bird-background",
		},
		info: "Plopp die Ballons!",
		subgrid: [
			["cl_IbhaluniInputs", "center"],
			["cl_IbhaluniCanvas", "center"],
		],
	},
	cl_Linaha: {
		userSelected: true,
		contentGroup: "Games",
		name: "Linaha",
		heritage: ["sesotho", "Länder"],
		source: {
			Daten: "https://restcountries.com/",
		},
		info: "Erweitere dein Wissen in Geographie!",
		subgrid: [
			["cl_LinahaOptionsA", "center"],
			["cl_LinahaOptionsB", "left"],
			["cl_LinahaOptionsC", "left"],
			["cl_LinahaOptionsStart", "left", "center"],
			["cl_LinahaQuestion", "center"],
			["cl_LinahaRounds", "right"],
			["cl_LinahaScore", "right"],
			["cl_LinahaMap", "left", "center"],
			["cl_LinahaAnswers", "center"],
		],
	},
	cl_Lotto: {
		userSelected: true,
		logReqUser: false,
		width: 2,
		contentGroup: "Games",
		name: "Lotto",
		source: {
			Zahlen: "https://github.com/JohannesFriedrich/LottoNumberArchive",
			Daten: "https://www.npmjs.com/package/norsk-tipping",
		},
		info: "Lotto / Eurojackpot",
		subgrid: [
			["cl_LottoOptionsA", "center"],
			["cl_LottoOptionsB", "center"],
			["cl_LottoSavedGame", "center"],
			["cl_LottoGetGames", "center"],
			["cl_LottoTabGames", "center"],
			["cl_LottoCanvas", "center"],
			["cl_LottoOverview", "center"],
		],
	},
	cl_Numbery: {
		userSelected: true,
		contentGroup: "Games",
		name: "Numbery",
		heritage: ["indonesisch", "nummeriert"],
		source: {
			Amazon: "https://www.iconfinder.com/iconsets/life-of-amazon-outline",
			Camping: "https://www.iconfinder.com/iconsets/camp-2",
			Furniture: "https://www.iconfinder.com/iconsets/furniture-269",
			Sport: "https://www.iconfinder.com/iconsets/sports-android-l-lollipop-icon-pack",
			SeaAnimals: "https://www.iconfinder.com/iconsets/under-the-sea-7",
			Zoo: "https://www.iconfinder.com/iconsets/zoo-line-welcome-to-zootopia",
		},
		info: "Klassisches Memory!",
		subgrid: [
			["cl_NumberyInputs", "left"],
			["cl_NumberyPlayers", "left"],
			["cl_NumberyPairs", "left"],
			["cl_NumberyCathegory", "left"],
			["cl_NumberyPlayerNum", "left"],
			["cl_NumberyResult", "left"],
			["cl_NumberyImages", "center", "center"],
		],
	},
	cl_RayCaster: {
		userSelected: true,
		width: 2,
		height: 2,
		contentGroup: "Games",
		name: "RayCaster",
		source: {
			Code1: "https://ncase.me/sight-and-light/",
			Code2: "https://thecodingtrain.com/CodingChallenges/010.4-maze-dfs-p5.html",
		},
		info: 'Du bist der "blaue" und willst den grünen Punkt erreichen. Bewegen kannst du dich mit den Pfeiltasten. Drücke "x" um deine aktuelle Position zu markieren. Aber beachte: du hast nur 5 Markierungen!',
		subgrid: [
			["cl_RayCasterInputs", "left"],
			["cl_RayCasterSpeed", "left"],
			["cl_RayCasterSize", "left"],
			["cl_RayCasterView", "left"],
			["cl_RayCasterOptionsA", "left"],
			["cl_RayCasterOptionsB", "left"],
			["cl_RayCasterOptionsC", "left"],
			["cl_RayCasterOptionsD", "left"],
			["cl_RayCasterCanvas", "center"],
		],
	},
	cl_Sudoku: {
		userSelected: true,
		width: 2,
		height: 2,
		contentGroup: "Games",
		name: "Sudoku",
		source: {
			Code: "https://github.com/boggan/js-sudoku-generator#readme",
			Puzzels: "https://www.kaggle.com/bryanpark/sudoku",
		},
		info: "Klassisches Sudoku-Puzzle.<br>Durch Eingabe einer Zahl mittels Tastatur kannst du die Zahl eintragen. Durch drücken der Leertaste kannst du die Eingabeart direkt wechseln. Mit SHIFT kannst du mehere Zellen gleichzeitig auswählen.",
		subgrid: [
			["cl_SudokuGetBoard", "center"],
			["cl_SudokuTimer", "left"],
			["cl_SudokuOptionsA", "left"],
			["cl_SudokuOptionsB", "left"],
			["cl_SudokuOptionsC", "left"],
			["cl_SudokuInput", "left"],
			["cl_SudokuOverview", "left", "start"],
			["cl_SudokuCanvas", "center"],
		],
	},
	cl_Sweeper: {
		userSelected: true,
		width: 2,
		height: 2,
		contentGroup: "Games",
		name: "Sweeper",
		heritage: ["englisch", "Kehrmaschine"],
		source: {
			Code: "https://thecodingtrain.com/CodingChallenges/071-minesweeper.html",
		},
		info: "Klassisches Mine-Sweeper!",
		subgrid: [
			["cl_SweeperCanvas", "center"],
			["cl_SweeperInputs", "center"],
			["cl_SweeperGrid", "center"],
			["cl_SweeperSweeps", "center"],
		],
	},
	//News
	cl_Howa: {
		userSelected: true,
		width: 2,
		contentGroup: "News",
		globalValString: "idVin_howaEntry",
		name: "Howa",
		heritage: ["turkmenisch", "Wetter"],
		source: {
			Daten: "https://openweathermap.org",
		},
		info: "Wettervorhersage in 3 Stunden abständen für die nächsten 4 Tage.",
		subgrid: [
			["cl_HowaInput", "center", "end"],
			["cl_HowaNow", "center", "end"],
			["cl_HowaOptionsA", "left"],
			["cl_HowaOptionsB", "left"],
			["cl_HowaOptionsC", "left"],
			["cl_HowaGraph", "center"],
			["cl_HowaZoom", "center"],
			["cl_HowaMapsExpand", "center"],
			["cl_HowaMapsSelectCountry", "right"],
			["cl_HowaMapsSelectCriteria", "left"],
			["cl_HowaMapsImg", "center"],
		],
	},
	cl_Lions: {
		userSelected: true,
		active: false,
		contentGroup: "News",
		name: "Lions",
		heritage: ["englisch", "Löwen"],
		source: {
			Daten: "https://hirsau.lions.de/",
		},
		info: "Gewinner des Lions-Advendskalender 2021 - Edition Nagold",
		subgrid: [
			["cl_LionsInput", "right", "center"],
			["cl_LionsOutput", "left"],
			["cl_LionsTable", "center"],
		],
	},
	cl_News: {
		userSelected: true,
		contentGroup: "News",
		name: "News",
		heritage: ["englisch", "Nachrichten"],
		source: {
			Daten: "https://newsdata.io",
		},
		subgrid: [
			["cl_NewsCategory", "left"],
			["cl_NewsCountry", "left"],
			["cl_NewsTable", "left"],
			["cl_NewsResultTitle", "center", "center"],
			["cl_NewsResultText", "center"],
			["cl_NewsResultImage", "center"],
		],
	},
	cl_PostillonTicker: {
		userSelected: true,
		contentGroup: "News",
		name: "PostillonTicker",
		source: {
			Daten: "https://www.der-Postillon.com",
		},
		info: "Alle Postillon News-Ticker zum durchklicken",
		subgrid: [
			["cl_PostillionTable", "center"],
			["cl_PostillionNumber", "center"],
		],
	},
	cl_Sepakbola: {
		userSelected: false,
		height: 2,
		active: false,
		contentGroup: "News",
		name: "Sepakbola",
		heritage: ["javanisch", "Fußball"],
		source: {
			Daten: "https://www.openligadb.de",
		},
		subgrid: [
			["cl_SepakbolaInputLiga", "left"],
			["cl_SepakbolaInputSeason", "left"],
			["cl_SepakbolaInputDay", "center"],
			["cl_SepakbolaTable", "right"],
			["cl_SepakbolaMatches", "left"],
		],
	},
	//Tools
	cl_Blechgeometrie: {
		userSelected: true,
		logReqUser: true,
		contentGroup: "Tools",
		globalValNumber: "idVin_blechgeoDicke",
		name: "Blechgeometrie",
		source: {
			Daten: "https://rime.de/de/wiki/lochabstand-berechnen/",
		},
		subgrid: [
			["cl_BlechgeoVinDicke", "center"],
			["cl_BlechgeoVinRadius", "center"],
			["cl_BlechgeoVinForm", "center"],
			["cl_BlechgeoVinBreite", "center"],
			["cl_BlechgeoLblResult", "center"],
			["cl_BlechgeoImg", "center"],
		],
	},
	cl_Expansion: {
		userSelected: true,
		contentGroup: "Tools",
		globalValNumber: "idVin_expansionLength",
		name: "Expansion",
		heritage: ["englisch", "Ausdehnung"],
		source: {
			Daten: "https://www.schweizer-fn.de/stoff/waermedehnung/waermedehnung.php#stahltabelle",
		},
		subgrid: [
			["cl_ExpansionMaterialsA", "right"],
			["cl_ExpansionMaterialSwitch", "center"],
			["cl_ExpansionMaterialsB", "left"],
			["cl_ExpansionVinLength", "center"],
			["cl_ExpansionVinBaseTemperature", "center"],
			["cl_ExpansionVinTemperature", "center"],
			["cl_ExpansionCBOptions", "center", "center"],
			["cl_ExpansionList", "center"],
		],
	},
	cl_Geometrie: {
		userSelected: true,
		contentGroup: "Tools",
		globalValNumber: "idVin_Area_0",
		name: "Geometrie",
		subgrid: [
			["cl_GeometrieAreaSelect", "left"],
			["cl_GeometrieAreaInputA", "center"],
			["cl_GeometrieAreaInputB", "center"],
			["cl_GeometrieAreaInputC", "center"],
			["cl_GeometrieOptions", "center"],
			["cl_GeometrieCanvas", "center", "start"],
			["cl_GeometrieTable", "center"],
		],
	},
	cl_Luas: {
		userSelected: true,
		contentGroup: "Tools",
		globalValNumber: "idVin_luasDiameter",
		name: "Luas",
		heritage: ["irisch", "Geschwindigkeit"],
		info: "Geschwindigkeiten übersetzen und darstellen",
		subgrid: [
			["cl_LuasVinAngularVin", "left"],
			["cl_LuasVinLinearVin", "left"],
			["cl_LuasOptAngularVin", "left"],
			["cl_LuasOptLinearVin", "left"],
			["cl_LuasResult", "center"],
			["cl_LuasCanvas", "center"],
		],
	},
	cl_Material: {
		userSelected: true,
		logReqUser: true,
		contentGroup: "Tools",
		name: "Material",
		source: {
			Daten: "https://www.schweizer-fn.de/festigkeit/festigkeitswerte/stahl/stahl_start.php",
		},
		subgrid: [
			["cl_MaterialPropertyCb", "left"],
			["cl_MaterialList", "left"],
			["cl_MaterialSearchOptions", "left"],
			// ["cl_MaterialSearchVin", "left"],
			// ["cl_MaterialSearchSel", "left"],
			// ["cl_MaterialSearchClose", "left"],
			["cl_MaterialSearchList", "left"],
		],
	},
	cl_Middle: {
		userSelected: true,
		contentGroup: "Tools",
		globalValNumber: "idVin_middleA",
		name: "Mittenberechnung",
		info: "Berechnet mit: (b-a) / 2",
		subgrid: [
			["cl_MiddleInput0", "center"],
			["cl_MiddleInput1", "center"],
			["cl_MiddleMid", "center"],
			["cl_MiddleDiff", "center"],
			["cl_MiddleCanvas", "center"],
		],
	},
	cl_Niska: {
		userSelected: true,
		source: {
			Regelgewinde: "https://de.wikipedia.org/wiki/Metrisches_ISO-Gewinde",
			Feingewinde: "http://gewindenormen.com",
			Berechnung: "https://www.schweizer-fn.de/maschinenelemente/schraube/schraubenverbindung.php",
		},
		contentGroup: "Tools",
		name: "Niska",
		height: 2,
		heritage: ["mazedonisch", "Gewinde"],
		subgrid: [
			["cl_NiskaHeaderInput", "center"],
			["cl_NiskaHeaderSelect", "center"],
			["cl_NiskaSize", "center"],
			["cl_NiskaPitch", "center"],
			["cl_NiskaSelect", "center"],
			["cl_NiskaStrengthClassA", "center"],
			["cl_NiskaStrengthClassB", "center"],
			["cl_NiskaList", "center"],
		],
	},
	cl_Pattern: {
		userSelected: true,
		logReqUser: true,
		width: 2,
		contentGroup: "Tools",
		globalValNumber: "idVin_Pattern0",
		name: "Pattern",
		heritage: ["englisch", "Muster"],
		subgrid: [
			["cl_PatternInputA", "center"],
			["cl_PatternInputB", "center"],
			["cl_PatternInputC", "center"],
			["cl_PatternInputD", "center"],
			["cl_PatternInputE", "center"],
			["cl_PatternCanvas", "center"],
		],
	},
	cl_Pormula: {
		userSelected: true,
		width: 2,
		contentGroup: "Tools",
		name: "Pormula",
		source: {
			Library: "https://github.com/Tom-Alexander/regression-js",
		},
		heritage: ["filipino", "Formel"],
		info: "Gleichung aus Datenpunkten ermitteln.",
		subgrid: [
			["cl_PormulaBestFit", "center"],
			["cl_PormulaTypeSelect", "center"],
			["cl_PormulaPolyFit", "center"],
			["cl_PormulaPrecision", "center"],
			["cl_PormulaOrder", "center"],
			["cl_PormulaInputs", "left"],
			["cl_PormulaAddInputs", "left"],
			["cl_PormulaPointEntryA", "center"],
			["cl_PormulaPointEntryB", "center"],
			["cl_PormulaPointEntryC", "center"],
			["cl_PormulaPointResultA", "center"],
			["cl_PormulaPointResultB", "center"],
			["cl_PormulaPointResultC", "center"],
			["cl_PormulaInfo", "center"],
			["cl_PormulaLblResult", "center"],
			["cl_PormulaAccuracy", "center"],
			["cl_PormulaCanvas", "center"],
		],
	},
	cl_Pythagoras: {
		userSelected: true,
		contentGroup: "Tools",
		globalValNumber: "idVin_Pytho_0",
		name: "Pythagoras",
		subgrid: [
			["cl_PythagorasInput0", "right"],
			["cl_PythagorasInput1", "right"],
			["cl_PythagorasInput2", "right"],
			["cl_PythagorasInput3", "right"],
			["cl_PythagorasInput4", "right"],
			["cl_PythagorasInfo", "center"],
			["cl_PythagorasCanvas", "left"],
		],
	},
	cl_Quickmath: {
		userSelected: true,
		contentGroup: "Tools",
		globalValNumber: "idVin_quickkmathVal",
		name: "Quickmath",
		subgrid: [
			["cl_QuickmathInput", "center"],
			["cl_QuickmathStart", "center"],
			["cl_QuickmathEnd", "center"],
			["cl_QuickmathListMultiply", "center"],
			["cl_QuickmathListDivide", "center"],
			["cl_QuickmathListPow", "center"],
		],
	},
	cl_Ranje: {
		userSelected: true,
		contentGroup: "Tools",
		globalValNumber: "idVin_ranjeVal",
		name: "Ranje",
		heritage: ["Haiti-Kreolisch", "anordnen"],
		subgrid: [
			["cl_RanjeInput", "center"],
			["cl_RanjeList", "center"],
		],
	},
	//Utility
	cl_BiktadA: {
		userSelected: true,
		contentGroup: "Utility",
		name: "BiktadA",
		heritage: ["schwedisch", "gebeichtet"],
		source: {
			Code: "https://stackoverflow.com/a/5918791",
		},
		info: "Diese Daten sind ohne deine Zustimmung im Browser verfügbar!",
		subgrid: [["cl_BiktadATable", "center"]],
	},
	cl_Boredom: {
		userSelected: true,
		contentGroup: "Utility",
		name: "Boredom",
		heritage: ["englisch", "Langeweile"],
		source: {
			Daten: "https://www.boredapi.com/",
		},
		subgrid: [
			["cl_BoredomStart", "center"],
			["cl_BoredomAnswer", "center"],
		],
	},
	cl_Botanicals: {
		userSelected: true,
		contentGroup: "Utility",
		name: "Botanicals",
		heritage: ["englisch", "botanisch"],
		source: {
			Daten: "https://www.tabelle.info/kraeuter.html",
		},
		subgrid: [
			["cl_BotanicalsVinPlant", "center"],
			["cl_BotanicalsVinDiscomfort", "center"],
			["cl_BotanicalsTabResultPlant", "center"],
			["cl_BotanicalsTabResultDiscomfort", "center"],
		],
	},
	cl_Egg: {
		userSelected: true,
		contentGroup: "Utility",
		name: "Eierkochen",
		source: {
			Daten: "newton.ex.ac.uk/teaching/CDHW/egg/",
		},
		info: "1. Ausreichnd Wasser zum kochen bringen.<br>2. Ei in leicht kochendes Wasser legen, sodass es vollständig bedeckt ist.<br>3. Timer starten.<br>4. Fertiges Ei aus kochendem Wasser entnehmen. Achtung, das Wasser ist heiß, das Ei auch!<br>5. Nach belieben unter kaltem Wasser abschrecken",
		subgrid: [
			["cl_EggMassValue", "center"],
			["cl_EggTempValue", "center"],
			["cl_EggYolkValue", "center"],
			["cl_EggStart", "center"],
			["cl_EggTime", "center"],
			["cl_EggTimeProgress", "center"],
		],
	},
	cl_Foody: {
		userSelected: true,
		contentGroup: "Utility",
		name: "Foody",
		heritage: ["vietnamesisch", "lecker"],
		info: "Wie lange und wie warm muss es kochen oder backen?<br>Suche ein Gericht aus und starte den Timer!",
		subgrid: [
			["cl_FoodyType", "left"],
			["cl_FoodyPreheat", "left"],
			["cl_FoodyStart", "center"],
			["cl_FoodyTime", "center"],
			["cl_FoodyTimeProgress", "center"],
		],
	},
	cl_Hverertu: {
		userSelected: true,
		contentGroup: "Utility",
		globalValString: "idVin_hverertuEntry",
		name: "Hver Ertu",
		heritage: ["isländisch", "Wer bist du"],
		source: {
			Alter: "https://agify.io",
			Herkunft: "https://nationalize.io",
			Gender: "https://genderize.io",
		},
		subgrid: [
			["cl_HverertuInput", "center"],
			["cl_HverertuTable", "center"],
		],
	},
	cl_Iomlaid: {
		userSelected: true,
		contentGroup: "Utility",
		globalValNumber: "idVin_IomlaidCur",
		name: "Iomlaid",
		active: false,
		heritage: ["schottisch-gälisch", "Austausch"],
		source: {
			Daten: "https://exchangerate.host",
		},
		subgrid: [
			["cl_IomlaidSelCur", "right"],
			["cl_IomlaidVinCur", "left"],
			["cl_IomlaidTab", "center"],
		],
	},
	cl_Kadar: {
		userSelected: true,
		contentGroup: "Utility",
		name: "Kadar",
		active: false,
		heritage: ["türkisch", "bis"],
		info: "Berechne Zeiten",
		subgrid: [
			["cl_KadarSelA", "center"],
			["cl_KadarSelB", "center"],
			["cl_KadarLblNow", "center"],
			["cl_KadarResultTable_Anow", "center"],
			["cl_KadarResultTable_AB", "center"],
			["cl_KadarResultTable_Bnow", "center"],
		],
	},
	cl_Kaihanga: {
		userSelected: true,
		contentGroup: "Utility",
		globalValString: "idVin_kaihangaEntry",
		name: "Kaihanga",
		heritage: ["maori", "Hersteller"],
		source: {
			Code: "http://dougtesting.net/home",
		},
		info: "Glücksrad!<br>Gib Gewinne ein und drücke auf das Rad.",
		subgrid: [
			["cl_KaihangaInput", "left"],
			["cl_KaihangaSegments", "left"],
			["cl_KaihangaResult", "left"],
			["cl_KaihangaCanvas", "left"],
		],
	},
	cl_Kounselor: {
		userSelected: true,
		contentGroup: "Utility",
		width: 1,
		name: "Kounselor",
		heritage: ["jiddisch", "Ratgeber"],
		subgrid: [
			["cl_KounselorOptionsA", "left"],
			["cl_KounselorOptionsB", "left"],
			["cl_KounselorOptionsC", "left"],
			["cl_KounselorOptionsD", "left"],
			["cl_KounselorOptionsE", "left"],
			["cl_KounselorOptionsF", "left"],
			["cl_KounselorOptionsG", "left"],
			["cl_KounselorOutputA", "right", "center"],
			["cl_KounselorOutputB", "right", "center"],
		],
	},
	cl_Netsaona: {
		userSelected: true,
		contentGroup: "Utility",
		name: "Netsaona",
		heritage: ["shona", "Zufall"],
		info: "Zufallsgenerator für verschiedene Dinge!",
		subgrid: [
			["cl_NetsaonaOptionsA", "center"],
			["cl_NetsaonaOptionsB", "center"],
			["cl_NetsaonaOptionsC", "center"],
			["cl_NetsaonaOptionsD", "center"],
			["cl_NetsaonaOptionsE", "center"],
			["cl_NetsaonaOptionsF", "center"],
			["cl_NetsaonaOptionsG", "center"],
			["cl_NetsaonaOutput", "center"],
		],
	},
	cl_Pelvelea: {
		userSelected: true,
		contentGroup: "Utility",
		name: "Pelvelea",
		heritage: ["khmer", "Zeit"],
		info: "Wann kannst du nach Hause?!",
		subgrid: [
			["cl_PelveleaStarttime", "center"],
			["cl_PelveleaBreaks", "center"],
			["cl_PelveleaWorktime", "center"],
			["cl_PelveleaResult", "center"],
			["cl_PelveleaProgress", "center"],
			["cl_PelveleaBreaktime", "center"],
		],
	},
	cl_PlatLesen: {
		userSelected: true,
		contentGroup: "Utility",
		name: "PlatLesen",
		heritage: ["malaysisch", "Nummernschild"],
		source: {
			Daten: "https://www.wbrnet.info/db/9964.html",
		},
		subgrid: [
			["cl_PlatLesenNumInput", "center"],
			["cl_PlatLesenRegInput", "center"],
			["cl_PlatLesenResult", "center"],
		],
	},
	cl_Thiontu: {
		userSelected: true,
		contentGroup: "Utility",
		globalValString: "idArea_thiontuInputEntry",
		name: "Thiontu",
		heritage: ["irisch", "umwandeln"],
		subgrid: [
			["cl_ThiontuInputArea", "right"],
			["cl_ThiontuOutputArea", "left"],
			["cl_ThiontuOptions_A", "center"],
			["cl_ThiontuOptions_B", "center"],
			["cl_ThiontuOptions_C", "center"],
			["cl_ThiontuOptions_D", "center"],
			["cl_ThiontuOptions_E", "center"],
		],
	},
	cl_Tugas: {
		userSelected: true,
		contentGroup: "Utility",
		globalValString: "idArea_tugasEntry",
		name: "Tugas",
		heritage: ["indonesisch", "Pflicht"],
		info: 'Füge Texte ein und drück "Enter". Klicke auf einen deiner Texte und er kopiert sich direkt in deine Zwischenablage!',
		subgrid: [
			["cl_TugasInput", "center"],
			["cl_TugasEnter", "center"],
			["cl_TugasList", "left"],
		],
	},
	//Setings
	cl_GeneralSettings: {
		userSelected: true,
		contentGroup: "Global-Settings",
		name: "GeneralSettings",
		subgrid: [
			["cl_SettingsCopyClick", "left"],
			["cl_SettingsFontsize", "left"],
			["cl_SettingsCopySeparator", "left"],
			["cl_SettingsDecimals", "left"],
		],
	},
	cl_ColorSettings: {
		userSelected: true,
		contentGroup: "Global-Settings",
		name: "ColorSettings",
		subgrid: [
			["cl_ColourSettingsHeaderLight", "center"],
			["cl_ColourSettingsHeaderDark", "center", "end"],
			["cl_ColourSettings_light_0", "center"],
			["cl_ColourSettings_light_1", "center"],
			["cl_ColourSettings_light_2", "center"],
			["cl_ColourSettings_dark_0", "center"],
			["cl_ColourSettings_dark_1", "center"],
			["cl_ColourSettings_dark_2", "center"],
		],
	},
	cl_UserGridLayout: {
		userSelected: true,
		height: 2,
		contentGroup: "Global-Settings",
		name: "User-Layout",
		subgrid: [
			["cl_UserGridOptions", "center"],
			["cl_UserGridTable", "center"],
			// ["cl_UserGridCanvas", "center"],
		],
	},
	cl_MaterialFilterSettings: {
		userSelected: true,
		height: 2,
		contentGroup: "Global-Settings",
		name: "Materialfilter",
		subgrid: [["cl_MaterialFilterTable", "center"]],
	},
	cl_UserLogin: {
		userSelected: true,
		contentGroup: "Account-Settings",
		name: "Login or Register",
		subgrid: [
			["cl_UserLogin_mail", "left"],
			["cl_UserLogin_pass", "left"],
			["cl_UserLogin_submit", "left"],
			["cl_UserLogin_cancel", "left"],
			["cl_UserLogin_check", "left"],
			["cl_UserLogin_alert", "left"],
		],
	},
	cl_UserChange: {
		userSelected: true,
		contentGroup: "Account-Settings",
		name: "Change or Logout",
		subgrid: [
			["cl_UserChange_user", "left"],
			["cl_UserChange_infos", "left"],
			["cl_UserChange_change", "left"],
			["cl_UserChange_cancel", "left"],
			["cl_UserChange_logout", "left"],
		],
	},
};

export const contentFooter = [
	["Icons", "https://www.iconfinder.com/search/icons?family=feather"],
	["Canvas-Library", "https://p5js.org/"],
	["Charts", "http://chartJS.org"],
	["Date-Picker", "https://github.com/Pikaday/Pikaday"],
	["Inspirations", "https://thecodingtrain.com/"],
	["Color calculations", "https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color/3943023#3943023"],
	["Color calculations", "https://www.html-code-generator.com/javascript/color-converter-script"],
];
