import { initEL, KadRandom } from "../KadUtils/KadUtils.js";

initEL({ id: idBtn_boredomStart, fn: boredomGetActivityindex });
initEL({
  id: idSel_boredomLanguage,
  fn: boredomLanguageSelect,
  selList: [
    ["Deutsch", "de"],
    ["English", "en"],
  ],
});
const boredomOptions = {
  index: 0,
  language: "de",
};
export function clear_cl_Boredom() {
  idSel_boredomLanguage.KadReset();
  idArea_boredomAnswer.value = "";
  idArea_boredomAnswer.placeholder = "Activitätengenerator...";
  boredomStart();
}

function boredomGetActivityindex() {
  boredomOptions.index = KadRandom.randomIndex(boredomList[boredomOptions.language]);
  boredomStart();
}

function boredomLanguageSelect() {
  boredomOptions.language = idSel_boredomLanguage.KadGet();
  boredomStart();
}

function boredomStart() {
  idArea_boredomAnswer.value = `${boredomList[boredomOptions.language][boredomOptions.index]}.`;
}
const boredomList = {
  de: [
    "Lernen Sie Express.js",
    "Lernen Sie, jemanden in einer neuen Sprache zu begrüßen",
    "Lernen Sie, wie man eine neue Sportart ausübt",
    "Schreiben Sie einem Freund, mit dem Sie lange nicht gesprochen haben, eine SMS",
    "Lernen Sie eine neue Programmiersprache",
    "Lernen Sie, wie man einen Papierkranich faltet",
    "Finden Sie eine Heimwerkeraufgabe",
    "Lernen Sie den Goldenen Schnitt kennen",
    "Arbeiten Sie ehrenamtlich im örtlichen Tierheim",
    "Spielen Sie eine Partie Monopoly",
    "Backen Sie Gebäck für sich und Ihren Nachbarn",
    "Backen Sie etwas, das Sie noch nie probiert haben",
    "Gehen Sie mit Ihrem Hund spazieren",
    "Meditieren Sie fünf Minuten lang",
    "Beginnen Sie mit einem Buch, zu dessen Lektüre Sie noch nie gekommen sind",
    "Machen Sie ein Koffeinschläfchen",
    "Nehmen Sie ein Schaumbad",
    "Gehen Sie in ein Nagelstudio",
    "Hören Sie Ihr Lieblingsalbum",
    "Lernen Sie, ein neues Instrument zu spielen",
    "Bringen Sie Ihrem Hund einen neuen Trick bei",
    "Erstellen Sie eine To-do-Liste für Ihre Woche",
    "Gehen Sie mit einem Freund",
    "Machen Sie eine lange Autofahrt ohne Musik",
    "Sehen Sie sich einen Film an, den Sie sich normalerweise nie ansehen würden",
    "Gehen Sie mit ein paar Freunden ins Kino",
    "Zeichnen und malen Sie ein Mandala",
    "Räumen und organisieren Sie Ihr Zimmer",
    "Pflanzen Sie ein paar Blumentöpfe und stellen Sie sie im Haus auf",
    "Planen Sie einen Urlaub, den Sie schon immer machen wollten",
    "Gehen Sie mit Ihrer Katze spazieren",
    "Machen Sie mit ein paar Freunden ein Football-Trainingsspiel",
    "Füllen Sie eine Basketball-Tabelle aus",
    "Spielen Sie mit einem Freund eine Partie Tennis",
    "Treffen Sie sich mit einem Freund zum Mittagessen",
    "Lernen Sie Schlittschuhlaufen oder Rollschuhlaufen",
    "Gehen Sie mit ein paar Freunden zu einem Konzert mit lokalen Künstlern",
    "Erkunden Sie das Nachtleben Ihrer Stadt",
    "Reparieren Sie etwas, das in Ihrem Haus kaputt ist",
    "Waschen Sie Ihr Auto",
    "Finden Sie eine Wohltätigkeitsorganisation und spenden Sie dafür",
    "Veranstalten Sie einen Flohmarkt",
    "Spenden Sie Blut in einem lokalen Blutspendezentrum",
    "Arbeiten Sie ehrenamtlich und helfen Sie in einem Seniorenzentrum",
    "Kaufen Sie ein Unterstützen Sie Ihren lokalen Bauernmarkt",
    "Lernen Sie ein neues Rezept",
    "Erstellen Sie ein Kochbuch mit Ihren Lieblingsrezepten",
    "Legen Sie einen Komposthaufen an",
    "Arbeiten Sie ehrenamtlich bei Ihrer lokalen Lebensmittelbank",
    "Erstellen oder aktualisieren Sie Ihren Lebenslauf",
    "Malen Sie das Erste, was Sie sehen",
    "Starten Sie einen Blog für etwas, das Sie leidenschaftlich interessiert",
    "Legen Sie einen Garten an",
    "Mischen Sie Ihren Kleiderschrank auf und spenden Sie die Kleidung, aus der Sie herausgewachsen sind",
    "Informieren Sie sich über die Weltnachrichten",
    "Erstellen Sie eine persönliche Website",
    "Hören Sie sich einen neuen Podcast an",
    "Machen Sie mit ein paar Freunden einen Papierfliegerwettbewerb",
    "Lernen Sie Kalligrafie",
    "Legen Sie eine Sammlung an",
    "Gehen Sie in einen lokalen Secondhandladen",
    "Bauen Sie eine Couchfestung",
    "Sammeln Sie Müll in Ihrem Lieblingspark",
    "Kaufen Sie eine neue Hausdekoration",
    "Schreiben Sie einen Dankesbrief an eine einflussreiche Person in Ihrem Leben",
    "Räumen Sie Ihr Auto auf",
    "Schreiben Sie eine Kurzgeschichte",
    "Tun Sie etwas Nettes für jemanden, der Ihnen am Herzen liegt",
    "Denken Sie an ein neues Geschäft Idee",
    "Räumen Sie Ihre Garage auf",
    "Lernen Sie, einen Knopf anzunähen",
    "Lernen Sie, wie man einen französischen Zopf flechtet",
    "Lernen Sie, mit Ihren Fingern zu pfeifen",
    "Lernen Sie, mit Ihrer nicht-dominanten Hand zu schreiben",
    "Backen Sie Brot von Grund auf",
    "Erstellen Sie ein Budget",
    "Lernen Sie, wie man in Kurzschrift schreibt",
    "Bauen Sie ein einfaches Musikinstrument",
    "Gehen Sie ins Fitnessstudio",
    "Probieren Sie ein Essen, das Sie nicht mögen",
    "Überwinden Sie eine Ihrer Ängste",
    "Gehen Sie mit ein paar Freunden auf ein Konzert",
    "Gehen Sie in die Bibliothek und suchen Sie sich ein interessantes Buch",
    "Gehen Sie in einen Escape Room",
    "Gehen Sie mit ein paar Freunden in eine Karaoke-Bar",
    "Streichen Sie ein Zimmer in Ihrem Haus neu",
    "Spielen Sie einem Ihrer Freunde einen harmlosen Streich",
    "Machen Sie mit ein paar Freunden einen spontanen Roadtrip",
    "Gehen Sie Sterne beobachten",
    "Laden Sie ein paar Freunde zu einem Spieleabend ein",
    "Machen Sie selbstgemachtes Eis",
    "Fangen Sie ein Tagebuch an",
    "Gehen Sie mit ein paar Freunden auf ein Musikfestival",
    "Bauen Sie einen Eimer Liste",
    "Schauen Sie sich eine angesagte Serie am Stück an",
    "Lernen Sie, wie man eine Website erstellt",
    "Erstellen und befolgen Sie einen Sparplan",
    "Sehen Sie sich einen klassischen Film an",
    "Planen Sie eine Reise in ein anderes Land",
    "Lernen Sie, wie das Internet funktioniert",
    "Machen Sie eine Wanderung in einem örtlichen Park",
    "Machen Sie Batik-Shirts",
    "Erstellen Sie ein Sammelalbum mit Bildern Ihrer schönsten Erinnerungen",
    "Machen Sie ein Picknick mit ein paar Freunden",
    "Machen Sie ein Lagerfeuer mit Ihren engen Freunden",
    "Merken Sie sich die fünfzig Bundesstaaten und ihre Hauptstädte",
    "Besuchen Sie einen Kurs in Ihrem örtlichen Gemeindezentrum, der Sie interessiert",
    "Lösen Sie ein Problem, das Sie aufgeschoben haben",
    "Finden Sie einen neuen Freund",
    "Lernen Sie Origami",
    "Lernen Sie, wie man eine French Press benutzt",
    "Lesen Sie eine formelle Forschungsarbeit zu einem interessanten Thema",
    "Hören Sie sich ein neues Musikgenre an",
    "Arbeiten Sie ehrenamtlich in Ihrer örtlichen Lebensmittelausgabe",
    "Lernen Sie, wie man eine Alexa-Fähigkeit erstellt",
    "Überraschen Sie Ihren Lebensgefährten mit etwas rücksichtsvoll",
    "Lerne Kotlin",
    "Gehe laufen",
    "Lerne Holzbearbeitung",
    "Gründe eine Band",
    "Koche etwas zusammen mit jemandem",
    "Mach eine Jam-Session mit deinen Freunden",
    "Lerne GraphQL",
    "Spiele Basketball mit einer Gruppe von Freunden",
    "Lerne die chinesische Erhu",
    "Starte ein Webinar zu einem Thema deiner Wahl",
    "Lerne, wie man einen Arduino benutzt",
    "Sieh dir eine Broadway-Produktion an",
    "Lerne Javascript",
    "Besuche deine früheren Lehrer",
    "Recherchiere ein Thema, das dich interessiert",
    "Höre Musik, die du schon lange nicht mehr gehört hast",
    "Mache einen Angelausflug mit ein paar Freunden",
    "Backe einen Kuchen mit ein paar Freunden",
    "Mach Yoga",
    "Besuche ein nahegelegenes Museum",
    "Mach eine Fotosession mit ein paar Freunden",
    "Beobachte den Sonnenuntergang oder den Sonnenaufgang",
    "Spiele ein Volleyballspiel mit ein paar Freunden",
    "Veranstalte einen Filmmarathon mit ein paar",
  ],
  en: [
    "Learn Express.js",
    "Learn to greet someone in a new language",
    "Learn how to play a new sport",
    "Text a friend you haven't talked to in a long time",
    "Learn a new programming language",
    "Learn how to fold a paper crane",
    "Find a DIY to do",
    "Learn about the Golden Ratio",
    "Volunteer at a local animal shelter",
    "Play a game of Monopoly",
    "Bake pastries for you and your neighbor",
    "Bake something you've never tried before",
    "Take your dog on a walk",
    "Meditate for five minutes",
    "Start a book you've never gotten around to reading",
    "Take a caffeine nap",
    "Take a bubble bath",
    "Go to a nail salon",
    "Listen to your favorite album",
    "Learn to play a new instrument",
    "Teach your dog a new trick",
    "Make a to-do list for your week",
    "Go swimming with a friend",
    "Go on a long drive with no music",
    "Watch a movie you'd never usually watch",
    "Go see a movie in theaters with a few friends",
    "Draw and color a Mandala",
    "Rearrange and organize your room",
    "Pot some plants and put them around your house",
    "Plan a vacation you've always wanted to take",
    "Take your cat on a walk",
    "Have a football scrimmage with some friends",
    "Fill out a basketball bracket",
    "Play a game of tennis with a friend",
    "Catch up with a friend over a lunch date",
    "Learn how to iceskate or rollerskate",
    "Go to a concert with local artists with some friends",
    "Explore the nightlife of your city",
    "Fix something that's broken in your house",
    "Wash your car",
    "Find a charity and donate to it",
    "Hold a yard sale",
    "Donate blood at a local blood center",
    "Volunteer and help out at a senior center",
    "Shop at support your local farmers market",
    "Learn a new recipe",
    "Create a cookbook with your favorite recipes",
    "Create a compost pile",
    "Volunteer at your local food bank",
    "Create or update your resume",
    "Paint the first thing you see",
    "Start a blog for something you're passionate about",
    "Start a garden",
    "Clean out your closet and donate the clothes you've outgrown",
    "Catch up on world news",
    "Create a personal website",
    "Listen to a new podcast",
    "Have a paper airplane contest with some friends",
    "Learn calligraphy",
    "Start a collection",
    "Go to a local thrift shop",
    "Make a couch fort",
    "Pick up litter around your favorite park",
    "Buy a new house decoration",
    "Write a thank you letter to an influential person in your life",
    "Clean out your car",
    "Write a short story",
    "Do something nice for someone you care about",
    "Think of a new business idea",
    "Clean out your garage",
    "Learn to sew on a button",
    "Learn how to french braid hair",
    "Learn how to whistle with your fingers",
    "Learn to write with your nondominant hand",
    "Make bread from scratch",
    "Make a budget",
    "Learn how to write in shorthand",
    "Make a simple musical instrument",
    "Go to the gym",
    "Try a food you don't like",
    "Conquer one of your fears",
    "Go to a concert with some friends",
    "Go to the library and find an interesting book",
    "Go to an escape room",
    "Go to a karaoke bar with some friends",
    "Repaint a room in your house",
    "Pull a harmless prank on one of your friends",
    "Take a spontaneous road trip with some friends",
    "Go stargazing",
    "Invite some friends over for a game night",
    "Make homemade ice cream",
    "Start a daily journal",
    "Go to a music festival with some friends",
    "Make a bucket list",
    "Binge watch a trending series",
    "Learn how to make a website",
    "Create and follow a savings plan",
    "Watch a classic movie",
    "Plan a trip to another country",
    "Learn how the internet works",
    "Take a hike at a local park",
    "Make tie dye shirts",
    "Make a scrapbook with pictures of your favorite memories",
    "Have a picnic with some friends",
    "Have a bonfire with your close friends",
    "Memorize the fifty states and their capitals",
    "Take a class at your local community center that interests you",
    "Resolve a problem you've been putting off",
    "Make a new friend",
    "Learn origami",
    "Learn how to use a french press",
    "Read a formal research paper on an interesting subject",
    "Listen to a new music genre",
    "Volunteer at your local food pantry",
    "Learn how to make an Alexa skill",
    "Surprise your significant other with something considerate",
    "Learn Kotlin",
    "Go for a run",
    "Learn woodworking",
    "Start a band",
    "Cook something together with someone",
    "Have a jam session with your friends",
    "Learn GraphQL",
    "Play basketball with a group of friends",
    "Learn the Chinese erhu",
    "Start a webinar on a topic of your choice",
    "Learn how to use an Arduino",
    "Go see a Broadway production",
    "Learn Javascript",
    "Visit your past teachers",
    "Research a topic you're interested in",
    "Listen to music you haven't heard in a while",
    "Go on a fishing trip with some friends",
    "Bake a pie with some friends",
    "Do yoga",
    "Visit a nearby museum",
    "Have a photo session with some friends",
    "Watch the sunset or the sunrise",
    "Play a volleyball match with some friends",
    "Host a movie marathon with some friends",
    "Hold a video game tournament with some friends",
    "Write a poem",
    "Take a nap",
    "Mow your lawn",
    "Practice coding in your favorite lanaguage",
    "Write a song",
    "Play a video game",
    "Clean out your refrigerator",
    "Study a foreign language",
    "Learn the NATO phonetic alphabet",
    "Solve a Rubik's cube",
    "Make your own LEGO creation",
    "Plant a tree",
    "Contribute code or a monetary donation to an open-source software project",
    "Uninstall unused apps from your devices",
    "Prepare a dish from a foreign culture",
    "Patronize a local independent restaurant",
    "Give your pet ten minutes of focused attention",
    "Explore a park you have never been to before",
    "Configure two-factor authentication on your accounts",
    "Create a meal plan for the coming week",
    "Watch a Khan Academy lecture on a subject of your choosing",
    "Shred old documents you don't need anymore",
    "Learn about a distributed version control system such as Git",
    "Write a note of appreciation to someone",
    "Draw something interesting",
    "Learn and play a new card game",
    "Write a list of things you are grateful for",
    "Organize a bookshelf",
    "Organize a cluttered drawer",
    "Organize your music collection",
    "Organize your movie collection",
    "Learn Morse code",
    "Go for a walk",
    "Mow your neighbor's lawn",
    "Compliment someone",
    "Draft your living will",
    "Prepare a 72-hour kit",
    "Color",
    "Organize your pantry",
    "Back up important computer files",
    "Memorize a favorite quote or poem",
    "Do something you used to do as a kid",
    "Organize your basement",
    "Sit in the dark and listen to your favorite music with no distractions",
    "Do a jigsaw puzzle",
    "Look at pictures and videos of cute animals",
    "Write a handwritten letter to somebody",
    "Match your storage containers with their lids",
    "Start a family tree",
    "Look at your finances and find one way to save money",
    "Organize your dresser",
    "Learn the periodic table",
    "Improve your touch typing",
    "Donate to your local food bank",
    "Learn how to beatbox",
  ],
};
