import { initEL, KadRandom } from "../KadUtils/KadUtils.js";

const Btn_boredomStart = initEL({ id: "idBtn_boredomStart", fn: boredomGetActivityindex });
const boredomOptions = {
  index: 0,
};
const Area_boredomAnswer = initEL({ id: "idArea_boredomAnswer", resetValue: "Activitätengenerator..." });

export function clear_cl_Boredom() {
  Area_boredomAnswer.KadReset();
  // Area_boredomAnswer.value = "";
  // Area_boredomAnswer.placeholder = "Activitätengenerator...";
  boredomGetActivityindex();
}

function boredomGetActivityindex() {
  boredomOptions.index = KadRandom.randomIndex(boredomList);
  boredomStart();
}

function boredomStart() {
  Area_boredomAnswer.KadSetValue(`${boredomList[boredomOptions.index]}.`);
}
const boredomList = [
  "Lernen Sie, jemanden in einer neuen Sprache zu begrüßen",
  "Lernen Sie, wie man eine neue Sportart ausübt",
  "Schreiben Sie einem Freund, mit dem Sie lange nicht gesprochen haben, eine Nachricht",
  "Lernen Sie eine neue Programmiersprache",
  "Lernen Sie, wie man einen Papierkranich faltet",
  "Finden Sie eine Heimwerkeraufgabe",
  "Lernen Sie den Goldenen Schnitt kennen",
  "Arbeiten Sie ehrenamtlich im örtlichen Tierheim",
  "Spielen Sie eine Partie Monopoly",
  "Backen Sie Gebäck für sich und Ihren Nachbarn",
  "Backen Sie etwas, das Sie noch nie probiert haben",
  "Gehen Sie mit Ihrem Hund spazieren",
  "Meditieren Sie fünf Minuten lang",
  "Beginnen Sie mit einem Buch, zu dessen Lektüre Sie noch nie gekommen sind",
  "Machen Sie ein Koffeinschläfchen",
  "Hören Sie Ihr Lieblingsalbum",
  "Lernen Sie, ein neues Instrument zu spielen",
  "Bringen Sie Ihrem Hund einen neuen Trick bei",
  "Gehen Sie mit einem Freund",
  "Machen Sie eine lange Autofahrt ohne Musik",
  "Sehen Sie sich einen Film an, den Sie sich normalerweise nie ansehen würden",
  "Gehen Sie mit ein paar Freunden ins Kino",
  "Zeichnen und malen Sie ein Mandala",
  "Räumen und organisieren Sie Ihr Zimmer",
  "Pflanzen Sie ein paar Blumentöpfe und stellen Sie sie im Haus auf",
  "Planen Sie einen Urlaub, den Sie schon immer machen wollten",
  "Gehen Sie mit Ihrer Katze spazieren",
  "Machen Sie mit ein paar Freunden ein Football-Trainingsspiel",
  "Füllen Sie eine Basketball-Tabelle aus",
  "Spielen Sie mit einem Freund eine Partie Tennis",
  "Treffen Sie sich mit einem Freund zum Mittagessen",
  "Lernen Sie Schlittschuhlaufen oder Rollschuhlaufen",
  "Gehen Sie mit ein paar Freunden zu einem Konzert mit lokalen Künstlern",
  "Erkunden Sie das Nachtleben Ihrer Stadt",
  "Reparieren Sie etwas, das in Ihrem Haus kaputt ist",
  "Waschen Sie Ihr Auto",
  "Finden Sie eine Wohltätigkeitsorganisation und spenden Sie dafür",
  "Veranstalten Sie einen Flohmarkt",
  "Spenden Sie Blut in einem lokalen Blutspendezentrum",
  "Arbeiten Sie ehrenamtlich und helfen Sie in einem Seniorenzentrum",
  "Kaufen Sie ein Unterstützen Sie Ihren lokalen Bauernmarkt",
  "Lernen Sie ein neues Rezept",
  "Erstellen Sie ein Kochbuch mit Ihren Lieblingsrezepten",
  "Legen Sie einen Komposthaufen an",
  "Arbeiten Sie ehrenamtlich bei Ihrer lokalen Lebensmittelbank",
  "Erstellen oder aktualisieren Sie Ihren Lebenslauf",
  "Malen Sie das Erste, was Sie sehen",
  "Starten Sie einen Blog für etwas, das Sie leidenschaftlich interessiert",
  "Legen Sie einen Garten an",
  "Mischen Sie Ihren Kleiderschrank auf und spenden Sie die Kleidung, aus der Sie herausgewachsen sind",
  "Informieren Sie sich über die Weltnachrichten",
  "Erstellen Sie eine persönliche Website",
  "Hören Sie sich einen neuen Podcast an",
  "Machen Sie mit ein paar Freunden einen Papierfliegerwettbewerb",
  "Lernen Sie Kalligrafie",
  "Legen Sie eine Sammlung an",
  "Gehen Sie in einen lokalen Secondhandladen",
  "Bauen Sie eine Couchfestung",
  "Sammeln Sie Müll in Ihrem Lieblingspark",
  "Kaufen Sie eine neue Hausdekoration",
  "Schreiben Sie einen Dankesbrief an eine einflussreiche Person in Ihrem Leben",
  "Räumen Sie Ihr Auto auf",
  "Schreiben Sie eine Kurzgeschichte",
  "Tun Sie etwas Nettes für jemanden, der Ihnen am Herzen liegt",
  "Denken Sie an ein neues Geschäft Idee",
  "Räumen Sie Ihre Garage auf",
  "Lernen Sie, einen Knopf anzunähen",
  "Lernen Sie, wie man einen französischen Zopf flechtet",
  "Lernen Sie, mit Ihren Fingern zu pfeifen",
  "Lernen Sie, mit Ihrer nicht-dominanten Hand zu schreiben",
  "Backen Sie Brot von Grund auf",
  "Erstellen Sie ein Budget",
  "Lernen Sie, wie man in Kurzschrift schreibt",
  "Bauen Sie ein einfaches Musikinstrument",
  "Gehen Sie ins Fitnessstudio",
  "Probieren Sie ein Essen, das Sie nicht mögen",
  "Überwinden Sie eine Ihrer Ängste",
  "Gehen Sie mit ein paar Freunden auf ein Konzert",
  "Gehen Sie in die Bibliothek und suchen Sie sich ein interessantes Buch",
  "Gehen Sie in einen Escape Room",
  "Gehen Sie mit ein paar Freunden in eine Karaoke-Bar",
  "Streichen Sie ein Zimmer in Ihrem Haus neu",
  "Spielen Sie einem Ihrer Freunde einen harmlosen Streich",
  "Machen Sie mit ein paar Freunden einen spontanen Roadtrip",
  "Gehen Sie Sterne beobachten",
  "Laden Sie ein paar Freunde zu einem Spieleabend ein",
  "Machen Sie selbstgemachtes Eis",
  "Fangen Sie ein Tagebuch an",
  "Gehen Sie mit ein paar Freunden auf ein Musikfestival",
  "Bauen Sie einen Eimer Liste",
  "Schauen Sie sich eine angesagte Serie am Stück an",
  "Lernen Sie, wie man eine Website erstellt",
  "Erstellen und befolgen Sie einen Sparplan",
  "Sehen Sie sich einen klassischen Film an",
  "Planen Sie eine Reise in ein anderes Land",
  "Lernen Sie, wie das Internet funktioniert",
  "Machen Sie eine Wanderung in einem örtlichen Park",
  "Machen Sie Batik-Shirts",
  "Erstellen Sie ein Sammelalbum mit Bildern Ihrer schönsten Erinnerungen",
  "Machen Sie ein Picknick mit ein paar Freunden",
  "Machen Sie ein Lagerfeuer mit Ihren engen Freunden",
  "Merken Sie sich die fünfzig Bundesstaaten und ihre Hauptstädte",
  "Besuchen Sie einen Kurs in Ihrem örtlichen Gemeindezentrum, der Sie interessiert",
  "Lösen Sie ein Problem, das Sie aufgeschoben haben",
  "Finden Sie einen neuen Freund",
  "Lernen Sie Origami",
  "Lernen Sie, wie man eine French Press benutzt",
  "Lesen Sie eine formelle Forschungsarbeit zu einem interessanten Thema",
  "Hören Sie sich ein neues Musikgenre an",
  "Arbeiten Sie ehrenamtlich in Ihrer örtlichen Lebensmittelausgabe",
  "Lernen Sie, wie man eine Alexa-Fähigkeit erstellt",
  "Überraschen Sie Ihren Lebensgefährten mit etwas rücksichtsvoll",
  "Lerne Kotlin",
  "Gehe laufen",
  "Lerne Holzbearbeitung",
  "Gründe eine Band",
  "Koche etwas zusammen mit jemandem",
  "Mach eine Jam-Session mit deinen Freunden",
  "Lerne GraphQL",
  "Spiele Basketball mit einer Gruppe von Freunden",
  "Lerne die chinesische Erhu",
  "Starte ein Webinar zu einem Thema deiner Wahl",
  "Lerne, wie man einen Arduino benutzt",
  "Sieh dir eine Broadway-Produktion an",
  "Lerne Javascript",
  "Besuche deine früheren Lehrer",
  "Recherchiere ein Thema, das dich interessiert",
  "Höre Musik, die du schon lange nicht mehr gehört hast",
  "Mache einen Angelausflug mit ein paar Freunden",
  "Backe einen Kuchen mit ein paar Freunden",
  "Mach Yoga",
  "Besuche ein nahegelegenes Museum",
  "Mach eine Fotosession mit ein paar Freunden",
  "Beobachte den Sonnenuntergang oder den Sonnenaufgang",
  "Spiele ein Volleyballspiel mit ein paar Freunden",
  "Veranstalte einen Filmmarathon mit ein paar",
];
